

        <div class="bread-crumbs-wrapper">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#" title="" itemprop="url">Home</a></li>
                    <li class="breadcrumb-item active">Privacy And Policy</li>
                </ol>
            </div>
        </div>
        <section>
            <div class="gray-bg bottom-padd210">
                <div class="sec-box bottom-padd140">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-lg-12">
                                <div class="sec-wrapper">
                                    <div class="row">
                             
                                        <div class="col-md-12 col-sm-12 col-lg-12">
                                            <div class="title2-wrapper">
                                                <h1 class="marginb-0" itemprop="headline">Privacy And Policy</h1>
                                            </div>
                                            <div class="remove-ext">
                                                <div class="row">
<h2><span style="font-weight: 400;">FastoFresh Customer Agreement</span></h2>
<p><span style="font-weight: 400;">This Agreement (the "Agreement") is a legal agreement between you and Pick Fresh Foods (sole owner of its brand "FastoFresh" &amp; &ldquo;FastoFresh.com&rdquo;) that states the terms and conditions under which you may receive the FastoFresh Service and use the FastoFresh Web site ("FastoFresh.com").</span></p>
<h2><span style="font-weight: 400;">You agree to these terms &amp; conditions when using the FastoFresh Service or FastoFresh.com</span></h2>
<h2><span style="font-weight: 400;">1. FastoFresh Service:</span></h2>
<p><span style="font-weight: 400;">The FastoFresh Service is a transaction, information and communication service available to authorized users ("customers") who access FastoFresh.com. FastoFresh.com currently provides an online grocery shopping and delivery service, and may in the future provide additional shopping and related services.</span></p>
<p><span style="font-weight: 400;">FastoFresh.com's employees, agents or designees will shop and deliver grocery orders placed with the FastoFresh Service. Prices of products sold online may differ from those in retail stores. Delivery will be made to the delivery address that you specify when you confirm your order. Prices for products you place in your cart will be guaranteed for the transaction. Payment for groceries and associated shopping and delivery fees is due at the time of delivery. You are responsible for ensuring that someone is present at the delivery address to receive and pay for deliveries at the specified time of delivery. Anyone at the delivery address who receives the delivery is conclusively presumed to be authorized to receive and pay for the order. If FastoFresh.com cannot deliver your order, or must make an additional delivery because no one is at the delivery address to receive and pay for the order at the specified time, or wrong address / details given to us by you, will be assessed an additional fee. If you are not satisfied for any reason with an item purchased through the FastoFresh Service, you may call customer service at the time of receiving your order at&hellip;&hellip;&hellip;&hellip;.. FastoFresh.com's liability for missing a delivery is limited to delivery at a later agreed time at no additional charge.</span></p>
<p><strong>(a) Pricing:</strong><span style="font-weight: 400;">&nbsp;All the products listed on FastoFresh.com will be sold at MRP unless otherwise specified. The prices mentioned at the time applicable prices at the time of placing an order. Although prices of most of the products do not fluctuate on a daily basis but some of the commodities and fresh food do change on a daily basis which would be updated almost immediately on the portal.</span></p>
<p><strong>(b) Cancellation Policy:</strong><span style="font-weight: 400;">&nbsp;As a policy we do not cancel any order after it customer can cancel your is placed on the portal. However, if there are changes in the delivery slot time you requested or need to add more products, you need to call us on customer care number&hellip;&hellip;&hellip;&hellip;.. Please note: If we suspect any fraudulent transaction by any customer or any transaction which defies the terms &amp; conditions of using the website, we at our sole discretion could cancel such orders. We will maintain a negative list of all fraudulent transactions and customers and would deny access to them or cancel any orders placed by them.</span></p>
<p><strong>(c) Return &amp; Refunds:</strong><span style="font-weight: 400;">&nbsp;We have a "no questions asked return and refund policy" which entitles all our members to return the product at the time of delivery if due to some reason they are not satisfied with the quality or freshness of the product. We will take the returned product back with us and make the necessary adjustments to your order value. However, please note that no refund will be issues if a product is returned due to a change in mind or order is cancelled after it is packed or out for delivery.</span></p>
<p><strong>(d) Referrals:</strong><span style="font-weight: 400;">&nbsp;FastoFresh reserves the right to, at its sole discretion, withhold or withdraw a referral bonus. Invalid referrals include, but are not limited to:</span></p>
<ol>
<li><span style="font-weight: 400;"> Duplicate accounts belonging to the same individual</span></li>
<li><span style="font-weight: 400;"> Members staying in the same postal address</span></li>
<li><span style="font-weight: 400;"> Any other misuse, as determined by FastoFresh</span></li>
</ol>
<h2><span style="font-weight: 400;">2.Product Content:</span></h2>
<p><span style="font-weight: 400;">Product images are for representative purposes only. Every effort is made to maintain accurate and up to date product related content on FastoFresh. However, information provided is sourced from publicly available resources and hence FastoFresh does not claim responsibility or accept liability for any loss or damage due to use based on the same. We do not recommend relying solely on the product information provided. Packaging, product size, product contents &amp; nutritional information may change without any prior intimation.</span></p>
<h2><span style="font-weight: 400;">3.Property Rights:</span></h2>
<p><strong>(a) Copyright:</strong><span style="font-weight: 400;">&nbsp;All content on FastoFresh.com including, but not limited to, design, text, graphics, interfaces, and the selection and arrangement thereof, and all software are the property of FastoFresh.com, Pick Fresh Food ALL RIGHTS RESERVED, or its content providers. FastoFresh.com authorizes you to view and copy for the sole purpose of placing an order with FastoFresh.com, for your personal use, provided that you preserve any copyright or other proprietary notices. Any other use of materials on FastoFresh.com, including, but not limited to, reproduction, modification, distribution or publication for any commercial or public purposes, without the prior written permission of FastoFresh.com is strictly prohibited. FastoFresh.com reserves the right to revoke this authorization at any time, and any use shall be discontinued immediately on written notice from FastoFresh.com.</span></p>
<p><strong>(b) Trademarks:</strong><span style="font-weight: 400;">&nbsp;"FastoFresh,", "FastoFresh.com,", all FastoFresh.com logos, and all titles, characters, names, graphics and button icons are service marks, trademarks and/or trade dress of FastoFresh.com or otherwise proprietary to FastoFresh.com and may not be used by you for any reason other than as expressly permitted by this Agreement. All other trademarks, service marks, product names and company names or logos appearing on FastoFresh.com are the property of their respective owners.</span></p>
<h2><span style="font-weight: 400;">4. Your Account:</span></h2>
<p><span style="font-weight: 400;">You agree to provide FastoFresh.com with accurate and complete information as required by registration for the FastoFresh Service ("Customer Registration Data"), including, but not limited to, your legal name, billing and delivery addresses, telephone number and promptly to notify FastoFresh.com of any change in your Customer Registration Data at FastoFresh upon registration, your username and password will allow you to access the FastoFresh Service. Your password should be kept strictly confidential to prevent unauthorized use. You agree to notify FastoFresh.com promptly of any unauthorized use of your password or your account. You will remain liable for any use of the FastoFresh Service until you notify FastoFresh.com of the unauthorized use, loss or theft.</span></p>
<h2><span style="font-weight: 400;">5. Reviews, Comments, Communications, and other Contents:</span></h2>
<p><span style="font-weight: 400;">Visitors may post reviews, comments, and other content; and submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing on intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. FastoFresh.com reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content.</span></p>
<p><span style="font-weight: 400;">(i) You may not post, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights.</span></p>
<p><span style="font-weight: 400;">(ii) FastoFresh.com may review, edit, reject, refuse to post and/or delete any Content that in the sole judgment of FastoFresh.com violate these Terms of Use or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of another person.</span></p>
<p><span style="font-weight: 400;">(iii) Any information provided by you on this site shall not be misleading in any way.</span></p>
<h2><span style="font-weight: 400;">6. Unauthorized or Fraudulent Use:</span></h2>
<p><span style="font-weight: 400;">FastoFresh.com does not offer the FastoFresh Service to children. By registering for the FastoFresh Service, you warrant that you are at least 18 years old. If you are under 18, you may use the FastoFresh Service only with the involvement of a parent or guardian. From time to time, FastoFresh.com may extend promotional offers to existing or potential new customers. You agree to abide by the terms and conditions of any such offer and acknowledge that circumvention of the terms and conditions of such offers constitutes a fraudulent use. You will be liable for damages caused by such fraudulent use.</span></p>
<h2><span style="font-weight: 400;">7. Changes in Agreement or FastoFresh Service:</span></h2>
<p><span style="font-weight: 400;">FastoFresh.com may at any time change any of the terms of this Agreement but not limited to, the amount of, or basis for determining, any fees or charges for the FastoFresh Service. If FastoFresh.com makes material changes to this Agreement, FastoFresh.com will provide notice to you in a manner provided in this Agreement. Your use of the FastoFresh Service after any such change will be conclusively deemed acceptance of such change. FastoFresh.com may discontinue or revise any or all aspects of the FastoFresh Service without prior notice to you. Price and availability of products are also subject to change without notice. We reserve the right to correct online pricing errors. In such event, we reserve the right to correct the pricing error or cancel undelivered orders for such incorrectly priced products. You will be contacted in such circumstances. If any change is unacceptable to you, you may cancel your FastoFresh Service and terminate this Agreement.</span></p>
<h2><span style="font-weight: 400;">8. Disclaimer of Warranty and Limitation of Liability:</span></h2>
<p><span style="font-weight: 400;">Your use of the FastoFresh service, FastoFresh.com and the internet is entirely at your own risk. The FastoFresh service, FastoFresh.com and its contents are provided on an "as is", "as available" basis. To the fullest extent permitted by law FastoFresh.com disclaims all representations and warranties, including, but not limited to, warranties as to the availability, accuracy or content of information, products or services, and warranties of title, non-infringement, merchantability or fitness for a particular purpose. FastoFresh.com does not warrant that the functions provided by FastoFresh.com will be uninterrupted or error-free, or that FastoFresh.com or the server that makes it available are free from viruses or other harmful components.</span></p>
<p><span style="font-weight: 400;">Neither FastoFresh.com nor any of its directors, employees, agents, licensors or merchants (collectively, its "associates") shall be liable for damages of any kind, including, but not limited to, direct, indirect, incidental, punitive and consequential damages, arising from your use of, or inability to use, the FastoFresh service, FastoFresh.com, the internet or for any other claims related in any way to your relationship with FastoFresh.com.</span></p>
<h2><span style="font-weight: 400;">9. Indemnification:</span></h2>
<p><span style="font-weight: 400;">You agree to defend, indemnify and hold FastoFresh.com and its Associates harmless from any claims and expenses, including attorney's fees, arising in connection with a violation of this Agreement by you or through use of your account.</span></p>
<h2><span style="font-weight: 400;">10. Termination:</span></h2>
<p><span style="font-weight: 400;">FastoFresh.com may suspend or terminate your access to the FastoFresh Service at any time for any reason with or without notice to you. You may terminate your FastoFresh Service at any time for any reason by delivering notice in a manner provided in this Agreement which termination will be effective the day notice is received or such later date specified in the notice.</span></p>
<h2><span style="font-weight: 400;">11. Privacy and Security:</span></h2>
<p><span style="font-weight: 400;">Your privacy is very important to FastoFresh.com. Please click here to review a complete statement of our Privacy and Security Policy which also governs your use of FastoFresh.com and the FastoFresh Service.</span></p>
<p><span style="font-weight: 400;">(a) Aggregated Information. FastoFresh.com may use aggregated information regarding its customers and usage of the FastoFresh Service (such as customer demographics and traffic patterns) and disclose such aggregated information to advertisers, partners and others for various purposes.</span></p>
<p><span style="font-weight: 400;">(b) Third Party Service Providers. FastoFresh.com may employ other companies and individuals to perform certain functions such as delivering packages and analyzing data. They may have access to personal information to perform their functions.</span></p>
<p><span style="font-weight: 400;">(c) Sale of Business. FastoFresh.com may transfer Customer Registration Data and other personal information in connection with the sale of FastoFresh.com or the sale or transfer of its business operations in your geographic area to a third-party provider of grocery ordering or delivery services who agrees to be bound by this Privacy Policy until you consent that such information will be governed by the policies and terms of such third party provider.</span></p>
<p><span style="font-weight: 400;">(d) Enforcement of Agreement or Compliance with Law. FastoFresh.com may use or disclose personal information when FastoFresh.com believes it is appropriate to enforce this Agreement, to protect the rights, property or safety of FastoFresh.com or its users or to comply with the law.</span></p>
<h2><span style="font-weight: 400;">12. Notices:</span></h2>
<p><span style="font-weight: 400;">FastoFresh.com may give notice to you of a change in this Agreement and any other matter by general posting on FastoFresh.com, by electronic mail, or by conventional mail to your address contained in the Customer Registration Data.</span></p>
<h2><span style="font-weight: 400;">13. Legal and Miscellaneous:</span></h2>
<p><span style="font-weight: 400;">These Terms of Service constitute the entire agreement between the parties with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. The clauses as above shall survive the termination or expiry of this agreement. This electronic record is generated by a computer system and does not require any physical or digital signatures.</span></p>
<p><strong>(a) Arbitration</strong><span style="font-weight: 400;">&nbsp;If any dispute arises between you and FastoFresh.com during your use of the Website or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of the User Agreement and Terms and Conditions the dispute shall be first referred to a sole Arbitrator who shall be an independent and neutral third party identified by FastoFresh.com. The place of arbitration shall be Mumbai. The Arbitration &amp; Conciliation Act, 1996, shall govern the arbitration proceedings. The arbitration proceedings shall be in the English language.</span></p>
<p><strong>(b) Applicable law</strong><span style="font-weight: 400;">&nbsp;This site is created and controlled by FastoFresh.com. The laws of India shall apply and courts in Mumbai shall have jurisdiction in respect of all the terms, conditions and disclaimers. FastoFresh.com reserves the right to make changes to the website and the terms, conditions and disclaimers at any time and without information to the customers/users of the services/website of FastoFresh.com. Users are advised to regularly check for any amendments or updates to the terms and conditions contained herein.</span></p>
<h2><span style="font-weight: 400;">14. Terms and Conditions for OOH Campaign Offer:</span></h2>
<ul>
<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">FastoFresh.com is not liable to extend the offer to the customer if coupon code has not been applied while checkout</span></li>
<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">This offer cannot be encashed nor transferred</span></li>
<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Offer is not valid for bulk/institutional purchases</span></li>
<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">FastoFresh.com holds the exclusive right at its sole discretion to refuse or deny the offer to any registered user</span></li>
<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">FastoFresh.com reserves the right to disqualify any customer from the benefits of the campaign/offer, if any fraudulent activity is identified as being carried out by the customer for the purpose of availing the benefits under the campaign/offer or otherwise by use of the service</span></li>
<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">This offer may be withdrawn or extended at any time at the sole discretion of FastoFresh.com</span></li>
<li style="font-weight: 400;" aria-level="1"><span style="font-weight: 400;">Offer valid for Delhi-NCR only</span></li>
</ul>
                                                  



                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- Section Box -->
            </div>
        </section>

  